### ISSUE TITLE
Google Podcast - 404 incorrect URL

### ISSUE THREAD

**Issue by olekstomek** [allegro/podcast#35]
In URL you can find in URL incorrect value `[...]`:

- https://github.com/allegro/podcast/blob/8b8f08d772fe0ac26c1dcc854817b6e6ae732f19/src/_data/podcasts.json#L993
Should be:
`https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5idXp6c3Byb3V0LmNvbS84ODc5MTQucnNz/episode/QnV6enNwcm91dC0xMTc4Njg2NA?sa=X&ved=0CAUQkfYCahcKEwjg0Luc1tr7AhUAAAAAHQAAAAAQLw`

- https://github.com/allegro/podcast/blob/8b8f08d772fe0ac26c1dcc854817b6e6ae732f19/src/_data/podcasts.json#L931
Should be:
`https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5idXp6c3Byb3V0LmNvbS84ODc5MTQucnNz/episode/QnV6enNwcm91dC0xMTYxNDk2NQ?sa=X&ved=0CAUQkfYCahcKEwjg0Luc1tr7AhUAAAAAHQAAAAAQCg`

- https://github.com/allegro/podcast/blob/8b8f08d772fe0ac26c1dcc854817b6e6ae732f19/src/_data/podcasts.json#L964
Should be: `https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5idXp6c3Byb3V0LmNvbS84ODc5MTQucnNz/episode/QnV6enNwcm91dC0xMTY5NjgwOQ?sa=X&ved=0CAUQkfYCahcKEwjg0Luc1tr7AhUAAAAAHQAAAAAQLw`

Element: `/html/body/div[1]/section[1]/div/div/astro-island/div/div[2]/div[2]/ul/li[3]/a/img`
![image](https://user-images.githubusercontent.com/26818304/205267744-786aa143-706c-47b4-a9a5-c60abf3342d1.png)
It returns:

> 404. Wystąpił błąd.
> 
> Nie można znaleźć żądanego adresu URL na tym serwerze. To wszystko, co wiemy.

**Comment by mkosmul** [comment]
@marcinkuptel

**Comment by marcinkuptel** [comment]
@olekstomek Thank you for submitting an issue. The links are fixed now :)

**Comment by olekstomek** [comment]
Great, thanks. ;)
https://github.com/allegro/podcast/commit/a7ff4ef675a413385691ce30f83e13e8fee4d3d7
